import { describe, expect, it } from "vitest";
import {
  CAPABILITY_CONTRACT_VERSION,
  capabilityCacheKey,
  computeCapabilityFingerprint,
} from "../src/capability/fingerprint.js";

// ─── Test vectors (TAC-01) ─────────────────────────────────────────────────
// These vectors are the canonical reference for the fingerprint algorithm.
// Any change to the algorithm MUST update the vectors AND bump
// CAPABILITY_CONTRACT_VERSION to invalidate existing attestations.

describe("computeCapabilityFingerprint (TAC-01)", () => {
  it("produces a 64-char lowercase hex SHA-256 string", () => {
    const fp = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    expect(fp).toMatch(/^[0-9a-f]{64}$/);
  });

  it("is deterministic for the same inputs", () => {
    const opts = { actionRef: "v1.0.94", permissionsAllow: ["Bash(*)", "Write", "Edit"] };
    expect(computeCapabilityFingerprint(opts)).toBe(computeCapabilityFingerprint(opts));
  });

  it("test vector A: v1.0.94 / sorted [Bash(*),Edit,Write] / contract 1", () => {
    // Input (newline-separated):
    //   v1.0.94\n["Bash(*)","Edit","Write"]\n1
    // where the permissions are sorted and compact-JSON-serialised.
    const fp = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
      contractVersion: "1",
    });
    // Ground truth generated by: echo -n 'v1.0.94\n["Bash(*)","Edit","Write"]\n1' | sha256sum
    // We snapshot it here so any accidental algorithm change is detected.
    expect(fp).toMatchSnapshot();
  });

  it("test vector B: 40-char SHA / different permissionsAllow / contract 1", () => {
    const fp = computeCapabilityFingerprint({
      actionRef: "a".repeat(40),
      permissionsAllow: ["Bash(*)", "Write", "Edit", "Read"],
      contractVersion: "1",
    });
    expect(fp).toMatchSnapshot();
  });

  it("permissionsAllow order does not affect the fingerprint (canonical sort)", () => {
    const order1 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Write", "Bash(*)", "Edit"],
    });
    const order2 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    expect(order1).toBe(order2);
  });

  it("different actionRef produces a different fingerprint", () => {
    const fp1 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    const fp2 = computeCapabilityFingerprint({
      actionRef: "v1.0.95",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    expect(fp1).not.toBe(fp2);
  });

  it("different permissionsAllow produces a different fingerprint", () => {
    const fp1 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    const fp2 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write"],
    });
    expect(fp1).not.toBe(fp2);
  });

  it("different contractVersion produces a different fingerprint (invalidates old attestations)", () => {
    const fp1 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
      contractVersion: "1",
    });
    const fp2 = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
      contractVersion: "2",
    });
    expect(fp1).not.toBe(fp2);
  });

  it("uses CAPABILITY_CONTRACT_VERSION as default contractVersion", () => {
    const explicit = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
      contractVersion: CAPABILITY_CONTRACT_VERSION,
    });
    const implicit = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    expect(explicit).toBe(implicit);
  });
});

describe("capabilityCacheKey (TAC-02)", () => {
  it("returns a deterministic string prefixed with harness-capability-attestation-", () => {
    const fp = computeCapabilityFingerprint({
      actionRef: "v1.0.94",
      permissionsAllow: ["Bash(*)", "Write", "Edit"],
    });
    const key = capabilityCacheKey(fp);
    expect(key).toBe(`harness-capability-attestation-${fp}`);
    expect(key).toMatch(/^harness-capability-attestation-[0-9a-f]{64}$/);
  });

  it("different fingerprints produce different cache keys (no collisions)", () => {
    const fp1 = computeCapabilityFingerprint({ actionRef: "v1.0.94", permissionsAllow: ["Bash(*)", "Write", "Edit"] });
    const fp2 = computeCapabilityFingerprint({ actionRef: "v1.0.95", permissionsAllow: ["Bash(*)", "Write", "Edit"] });
    expect(capabilityCacheKey(fp1)).not.toBe(capabilityCacheKey(fp2));
  });
});
